class AppConstants {
  // YouTube API
  static const String youtubeApiKey = String.fromEnvironment(
    'YOUTUBE_API_KEY',
    defaultValue: 'AIzaSyDtKjoxQwWZK1zFv8BcbMB3uIyF4xI0B18',
  );
  static const String youtubeBaseUrl = 'https://www.googleapis.com/youtube/v3';
  static const int maxResults = 40;
  static const int searchMaxResults = 25;
  static const int prefetchPageCount = 2;

  // Optional remote feed server
  static const String feedApiBaseUrl = String.fromEnvironment(
    'FEED_API_BASE_URL',
    defaultValue: '',
  );

  // App Info
  static const String appName = 'Rannar Jogot';
  static const String appSubtitle = 'Bangladeshi Cooking Videos';
  static const String appTagline = 'Discover the flavors of Bangladesh';

  // Feed queries
  static const String latestFeedQuery =
      'বাংলাদেশী রান্না রেসিপি bangla cooking recipe';
  static const String trendingFeedQuery =
      'বাংলাদেশী রান্না recipe bangla cooking';

  // Search Queries for fetching Bangladeshi cooking videos
  static const List<String> searchQueries = [
    'বাংলাদেশী রান্না রেসিপি',
    'Bangladeshi cooking recipe',
    'Bengali recipe cooking',
    'বাংলা রান্না',
    'Bangla cooking tutorial',
    'desi cooking recipe bangla',
  ];

  // Cache Keys
  static const String cacheKeyPrefix = 'cached_videos_';
  static const String favoritesKey = 'favorite_videos';
  static const String searchHistoryKey = 'search_history';
  static const String themeKey = 'dark_mode';
  static const int videoCacheSchemaVersion = 2;
  static const int cacheDurationMinutes = 360;
  static const int feedCacheDurationMinutes = 360;
  static const int searchCacheDurationMinutes = 120;
}

class CategoryData {
  static const List<Map<String, dynamic>> categories = [
    {
      'id': 'fish',
      'nameEn': 'Fish Curry',
      'icon': '🐟',
      'gradient': ['0xFFFF6B35', '0xFFFF8E53'],
      'keywords': [
        'মাছ',
        'fish',
        'ilish',
        'ইলিশ',
        'রুই',
        'rui',
        'katla',
        'কাতলা',
        'pangash',
        'পাঙ্গাশ',
        'shorshe',
        'সর্ষে',
        'মাছের',
        'tilapia',
        'chingri',
        'চিংড়ি',
        'prawn',
        'shrimp',
        'hilsa',
        'machher',
        'fish curry',
        'fish fry',
        'মাছ ভাজা',
        'মাছের ঝোল',
        'telapia',
        'rohu',
        'carp',
        'salmon',
        'tuna',
        'পাবদা',
        'শিং',
        'মাগুর',
        'কই',
        'বোয়াল',
        'আইড়',
        'চিতল',
        'পুঁটি',
        'ট্যাংরা',
      ],
    },
    {
      'id': 'meat',
      'nameEn': 'Meat & Poultry',
      'icon': '🍗',
      'gradient': ['0xFFE53935', '0xFFFF5252'],
      'keywords': [
        'মাংস',
        'meat',
        'গরু',
        'beef',
        'মুরগি',
        'chicken',
        'mutton',
        'খাসি',
        'khasir',
        'lamb',
        'গোশত',
        'gosht',
        'kebab',
        'কাবাব',
        'tikka',
        'টিক্কা',
        'tandoori',
        'তন্দুরি',
        'roast',
        'রোস্ট',
        'মুরগির',
        'গরুর',
        'beef curry',
        'chicken curry',
        'kosha',
        'কষা',
        'ভুনা',
        'bhuna',
        'rezala',
        'রেজালা',
        'kacchi',
        'কাচ্চি',
        'steak',
        'wings',
        'drumstick',
        'liver',
        'কলিজা',
      ],
    },
    {
      'id': 'rice',
      'nameEn': 'Rice & Biryani',
      'icon': '🍚',
      'gradient': ['0xFFFF8F00', '0xFFFFB300'],
      'keywords': [
        'ভাত',
        'rice',
        'বিরিয়ানি',
        'biryani',
        'পোলাও',
        'pulao',
        'polao',
        'খিচুড়ি',
        'khichuri',
        'khichdi',
        'fried rice',
        'ফ্রাইড রাইস',
        'তেহারি',
        'tehari',
        'morog polao',
        'মোরগ পোলাও',
        'kacchi biryani',
        'কাচ্চি বিরিয়ানি',
        'pilaf',
        'চাল',
        'chawal',
        'jeera rice',
        'plain rice',
        'sticky rice',
        'নান',
        'রুটি',
        'পরোটা',
      ],
    },
    {
      'id': 'vegetables',
      'nameEn': 'Vegetables',
      'icon': '🥬',
      'gradient': ['0xFF43A047', '0xFF66BB6A'],
      'keywords': [
        'সবজি',
        'vegetable',
        'শাক',
        'ভর্তা',
        'bharta',
        'sabzi',
        'আলু',
        'aloo',
        'potato',
        'বেগুন',
        'begun',
        'eggplant',
        'brinjal',
        'লাউ',
        'lau',
        'gourd',
        'পটল',
        'potol',
        'ঝিঙ্গে',
        'করলা',
        'karola',
        'bitter gourd',
        'ফুলকপি',
        'cauliflower',
        'বাঁধাকপি',
        'cabbage',
        'veg',
        'নিরামিষ',
        'mixed vegetable',
        'labra',
        'লাবড়া',
        'chorchori',
        'চচ্চড়ি',
        'শাকের',
        'পালং',
      ],
    },
    {
      'id': 'snacks',
      'nameEn': 'Snacks & Street Food',
      'icon': '🥘',
      'gradient': ['0xFFFF6F00', '0xFFFFA000'],
      'keywords': [
        'নাস্তা',
        'snack',
        'ফুচকা',
        'fuchka',
        'চটপটি',
        'chotpoti',
        'সমুচা',
        'samosa',
        'সিঙ্গারা',
        'singara',
        'পিঠা',
        'pitha',
        'রোল',
        'roll',
        'চপ',
        'chop',
        'পকোড়া',
        'pakora',
        'ভাজা',
        'fry',
        'fried',
        'cutlet',
        'কাটলেট',
        'street food',
        'স্ট্রিট ফুড',
        'jhalmuri',
        'ঝালমুড়ি',
        'chanachur',
        'চানাচুর',
        'মুড়ি',
        'আচার',
        'pickle',
        'nimki',
        'নিমকি',
        'beguni',
        'বেগুনি',
        'alur chop',
        'আলুর চপ',
        'piaju',
        'পেঁয়াজু',
      ],
    },
    {
      'id': 'sweets',
      'nameEn': 'Sweets & Desserts',
      'icon': '🍮',
      'gradient': ['0xFFE91E63', '0xFFFF5C8D'],
      'keywords': [
        'মিষ্টি',
        'sweet',
        'পায়েস',
        'payesh',
        'সন্দেশ',
        'roshogolla',
        'রসগোল্লা',
        'mishti',
        'হালুয়া',
        'halwa',
        'halua',
        'জিলাপি',
        'jilapi',
        'jalebi',
        'সেমাই',
        'semai',
        'vermicelli',
        'ক্ষীর',
        'kheer',
        'dessert',
        'pudding',
        'পুডিং',
        'custard',
        'কাস্টার্ড',
        'মিষ্টান্ন',
        'গোলাপজাম',
        'gulab jamun',
        'রসমালাই',
        'rasmalai',
        'চমচম',
        'chomchom',
        'কালোজাম',
        'লাড্ডু',
        'বরফি',
        'firni',
        'ফিরনি',
        'doi',
        'দই',
        'yogurt',
        'curd',
      ],
    },
    {
      'id': 'dal',
      'nameEn': 'Dal & Lentils',
      'icon': '🍲',
      'gradient': ['0xFFFF9800', '0xFFFFC107'],
      'keywords': [
        'ডাল',
        'dal',
        'daal',
        'মসুর',
        'masoor',
        'মুগ',
        'moong',
        'mung',
        'lentil',
        'ছোলা',
        'chola',
        'chickpea',
        'বুটের',
        'boot',
        'মটর',
        'motor',
        'peas',
        'ডালের',
        'তড়কা',
        'tadka',
        'tempering',
        'সাম্বার',
        'sambar',
        'রসুন ডাল',
        'পাঁচমিশালি',
      ],
    },
    {
      'id': 'baking',
      'nameEn': 'Baking & Cakes',
      'icon': '🎂',
      'gradient': ['0xFF8E24AA', '0xFFAB47BC'],
      'keywords': [
        'কেক',
        'cake',
        'বিস্কুট',
        'biscuit',
        'baking',
        'বেকিং',
        'cookies',
        'কুকিজ',
        'bread',
        'রুটি',
        'পাউরুটি',
        'pastry',
        'পেস্ট্রি',
        'muffin',
        'মাফিন',
        'cupcake',
        'কাপকেক',
        'oven',
        'ওভেন',
        'brownie',
        'ব্রাউনি',
        'pizza',
        'পিৎজা',
        'doughnut',
        'ডোনাট',
        'pancake',
        'প্যানকেক',
        'waffle',
        'croissant',
      ],
    },
    {
      'id': 'drinks',
      'nameEn': 'Drinks & Beverages',
      'icon': '🥤',
      'gradient': ['0xFF00ACC1', '0xFF26C6DA'],
      'keywords': [
        'চা',
        'tea',
        'শরবত',
        'sherbet',
        'জুস',
        'juice',
        'smoothie',
        'স্মুদি',
        'লাচ্ছি',
        'lassi',
        'বোরহানি',
        'borhani',
        'কফি',
        'coffee',
        'milkshake',
        'মিল্কশেক',
        'পানীয়',
        'drink',
        'beverage',
        'lemonade',
        'লেমনেড',
        'মালটা',
        'আখের রস',
        'sugarcane',
        'দুধ চা',
        'masala tea',
        'মসলা চা',
        'iced tea',
        'mango shake',
      ],
    },
    {
      'id': 'festival',
      'nameEn': 'Festival & Special',
      'icon': '🎉',
      'gradient': ['0xFF6A1B9A', '0xFF9C27B0'],
      'keywords': [
        'ঈদ',
        'eid',
        'রমজান',
        'ramadan',
        'ইফতার',
        'iftar',
        'সেহরি',
        'sehri',
        'special',
        'স্পেশাল',
        'festival',
        'উৎসব',
        'পিঠা',
        'pitha',
        'নবান্ন',
        'nobanno',
        'পহেলা বৈশাখ',
        'boishakh',
        'দাওয়াত',
        'dawat',
        'party',
        'পার্টি',
        'wedding',
        'বিয়ে',
        'বিশেষ',
        'অনুষ্ঠান',
        'celebration',
        'মেহমানদারি',
      ],
    },
  ];
}
